### ISSUE TITLE
Учесть замечания к предыдщим проектам

### ISSUE THREAD

**Issue by coursar** [DamirZaripov16/wallpaper#1]
https://github.com/DamirZaripov16/gas

**Comment by DamirZaripov16** [comment]
@coursar, CodeCov также выделяет последнее условие
https://github.com/DamirZaripov16/wallpaper/blob/6d0d5c58170c8a62902246ae2fdd367eb5818ca4/src/app/wallpaper.js#L35-L43

**Comment by DamirZaripov16** [comment]
@coursar, CodeCov также выделяет последнее условие c 35-й линии
https://github.com/DamirZaripov16/wallpaper/blob/49a90841c1a1aab55797c2baabc46193badc052e/src/app/wallpaper.js#L35-L43
