### ISSUE TITLE
Домашнее задание

### ISSUE THREAD

**Issue by DamirZaripov16** [DamirZaripov16/wallpaper#2]
@coursar Добавил минимальный интерфейс.

**Comment by coursar** [comment]
Если вы посмотрите на то, что залилось: https://damirzaripov16.github.io/wallpaper/. То увидите, что не работает. А всё потому, что в .travis.yml у вас описано копирование папки js, а в проекте папка у вас app. Будьте аккуратнее и проверяйте, что залилось на сервер.
